# Generated by Django 5.2.7 on 2025-10-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_cateogry_rename_language_books_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogry',
            new_name='Category',
        ),
    ]
