# Generated by Django 5.2.7 on 2025-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_cateogry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Uzbek Literature', 'Uzbek Literature'), ('Russian Literature', 'Russian Literature'), ('English Literature', 'English Literature')], max_length=100, unique=True),
        ),
    ]
